### ISSUE TITLE
Improve active preset configuration should be in bold

### ISSUE THREAD

**Issue by GhaziTriki** [riadvice/bbbeasy#549]
**What is wrong with the current implementation? Please describe.**
Active preset configuration is not distinguishable.

**Describe the solution you'd like**
The active preset configuration should be in `bold` as bolder is not working.

**Screenshots/Designs**
Current status
![image](https://user-images.githubusercontent.com/4991088/233394201-31d611a1-4d5c-442f-afe0-1dc90125830b.png)

**Comment by fatenrakrouki123** [comment]
Fixed in PR: https://github.com/riadvice/bbbeasy/issues/549

**Comment by fatenrakrouki123** [comment]
Fixed in PR; https://github.com/riadvice/bbbeasy/pull/565
