### ISSUE TITLE
 Update language menu position to the end of the top bar

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#556]
**What is wrong with the current implementation? Please describe.**

the language  menu is not in the correct position .

**Describe the solution you'd like**

the position of the language menu should be updated to the end of the top bar 

**Screenshots/Designs**

![image](https://user-images.githubusercontent.com/108723664/233981112-d8b807aa-4243-427b-9649-8b14855aed14.png)

**Comment by GhaziTriki** [comment]
Still not
