### ISSUE TITLE
Load presets enters into an infinite loop .

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#575]
**Describe the bug**

Load presets enters into an infinite loop .

**To Reproduce**

1.Start the web app
2.Go to the presets page 

**Expected behavior**

Load presets should be done only once with a correct display

**Screenshots**

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment]
Actually user presets and user rooms are loaded in loop.
