### ISSUE TITLE
value too long for type character varying(32)

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#617]
**Describe the bug**

On the labels page when creating a name longer than 32 characters a problem appears

**To Reproduce**

1.Start the web app
2.Go to the labels page

**Expected behavior**

a popup should appear when creating a name with more than 32 characters .

**Screenshots**

![image](https://user-images.githubusercontent.com/108723664/235876124-6fca6bb5-d677-4849-a66c-91189ee2132b.png)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by marwa-benhassine** [comment]
A problem appears when editing  a name   longer than 32 characters 

![image](https://github.com/riadvice/bbbeasy/assets/108723664/164eb013-cbbc-4a9a-8463-34cc892aed63)

**Comment by GhaziTriki** [comment]
Duplicate of #618
