### ISSUE TITLE
Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#624]
**Describe the bug**

When opening the project in two pages and logging out of one, then back to the other and accessing any page, the error appears.

**To Reproduce**

1. Start the web app
2. Open the project in two windows  
3. Click the Sign Out button
4. Back to  the other window 
5. Click on rooms page 

**Expected behavior**

 The login page should appears instead of the error

**Screenshots**

![image](https://user-images.githubusercontent.com/108723664/235944587-caff4646-cd01-4a39-b8ef-f1ca70b10f1e.png)

**Desktop (please complete the following information):**

OS: Windows
Browser: Chrome/Edge/Firefox/opera

**Comment by GhaziTriki** [comment]
Can no more reproduce since frontend session check has been implemented.
