### ISSUE TITLE
improve bigbluebutton rooms settings popup

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#632]
**What is wrong with the current implementation? Please describe.**

Button placement should be improved

**Describe the solution you'd like**

buttons should be like this

![image](https://user-images.githubusercontent.com/108723664/236161939-984616f0-ed1c-48aa-8486-a6d2bdb48263.png)

**Screenshots/Designs**

![image](https://user-images.githubusercontent.com/108723664/236156726-2dcc3029-21fa-4824-832e-03cefca9e422.png)

**Comment by CherifAmine** [comment]
Fixed in PR: https://github.com/riadvice/bbbeasy/pull/651

**Comment by GhaziTriki** [comment]
We need to revert the previous width.

**Comment by CherifAmine** [comment]
Done
fixed in PR : https://github.com/riadvice/bbbeasy/pull/741
