### ISSUE TITLE
PR #633 not improving button display in preset configuration

### ISSUE THREAD

**Issue by GhaziTriki** [riadvice/bbbeasy#641]
**Describe the bug**
The #633 introduced some improvements in the buttons of the presets but added a visual regression in the installer preset configuration popup.

Linked to #632

**To Reproduce**
1. Go to step 3 in the installer.
2. Open a preset group.

**Expected behavior**
The buttons should be displayed a designed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/236483997-ac09d559-4737-4b26-a4c0-9a9e1552f64f.png)

**Comment by marwa-benhassine** [comment]
Items in the preset configuration are not aligned

![image](https://user-images.githubusercontent.com/108723664/236847596-5c6ad3c4-ed60-48db-991e-1287a83e2229.png)

**Comment by marwa-benhassine** [comment]
@CherifAmine 

![image](https://github.com/riadvice/bbbeasy/assets/108723664/fbd47aa7-cf38-4ac7-99a0-f8d413d5612d)

bigbluebutton parameters should return to the line when the text is too long
