### ISSUE TITLE
the starting room   is not working 

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#681]
**Describe the bug**

the starting room  is not working 

**To Reproduce**

1..Start the web app
2.Go to the Room details pages
3.Click on the button start 
**Expected behavior**

The Start button  should  work 

**Screenshots**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/c8dd2250-bf5d-48a2-b34c-1de0eda1625a)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment]
This issue is related to the library assigning default values instead of considering null values.
