### ISSUE TITLE
The system does not redirect to the authentication page

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#691]
**Describe the bug**

When opening the project in two pages and logging out of one, then back to the other and click on the bbbeasy logo  , the system does not redirect you to the authentication page

**To Reproduce**

1. Start the web app
2. Open the project in two windows
3. Click the Sign Out button
4. Back to the other window
5. Click on the bbbeasy logo 

**Expected behavior**

The login page should appears 

**Screenshots**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/897fe76c-5a49-4922-9ec1-d99aad8d6e36)

**Desktop (please complete the following information):**

OS: Windows
Browser: Chrome/Edge/Firefox/opera

**Comment by GhaziTriki** [comment]
Fixed in the logout logic implementation.
