### ISSUE TITLE
Show a warning when the BigBlueButton server is not configured

### ISSUE THREAD

**Issue by GhaziTriki** [riadvice/bbbeasy#702]
**What is wrong with the current implementation? Please describe.**
When BigBlueButton API settings is not configured there is no way to know it.

**Describe the solution you'd like**
Display a warning icon before the user icon showing a notification at hover.
"BigBlueButton API is not configured on this instance. Please contact you administrator"

** Screenshot **
![image](https://github.com/riadvice/bbbeasy/assets/4991088/6723ddc1-47c8-4e6e-a345-a35652f6e2b9)

**Additional context**
Instead of hiding non-usable buttons we need to make them inactive.

**Comment by marwa-benhassine** [comment]
@fatenrakrouki123 

If no alert to show we should not see the following button

![image](https://github.com/riadvice/bbbeasy/assets/108723664/3eb05ba0-0446-44c5-9a1d-8564fcf91289)

**Comment by GhaziTriki** [comment]
1. Validation must be on the field. (no error pop window)
2. Join/Start button must be disabled in the field is not valid.
3. Labels are hidden for anonymous users.

![image](https://github.com/riadvice/bbbeasy/assets/4991088/87ef6326-d18b-46fb-8d2a-06b4726b39ce)

**Comment by marwa-benhassine** [comment]
When BigBlueButton server is not configured, no notification is displayed.

https://github.com/user-attachments/assets/4f6bd506-43af-47b7-8b80-7b642ec4c6c5

**Comment by GhaziTriki** [comment]
Working in a new fresh install.
