### ISSUE TITLE
Add a star next to the administrator's name 

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#721]
**What is wrong with the current implementation? Please describe.**

Add a star next to the administrator's name 

 of what you want should happen.

**Screenshots/Designs**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/0d918e90-37ce-41a5-beab-83362b8a83a4)

**Comment by GhaziTriki** [comment]
Working on dev, I have to test on staging server.
