### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/bbbeasy#739]
**Describe the bug**

The error appears when we do not create any room

**To Reproduce**

1. Start the web app
2. Go to the rooms page 
3. Reload the page

**Expected behavior**

**Screenshots**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/9c5556b8-0cbe-4a23-9fa7-df3c89cba4e9)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment]
Looks like a regression #606

**Comment by GhaziTriki** [comment]
Can no more reproduce.
